replicaCount: 2
image:
  repository: ikurtz-angular-frontend/tour-of-heroes
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: ikurtz-tourofheroes.canary-demos.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
